services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: c-jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: on-failure
    networks:
      - jenkins_net

volumes:
  jenkins_home:
    name: jenkins_home

networks:
  jenkins_net:
    name: jenkins_net